#!/usr/bin/env python3
"""Generate matched per-experiment configs for the claim ladder (one config = one method).
All share the same model/data/training; only cond/proj + loss switches + output dir differ.
This removes the 'all smoke scripts use one config' ambiguity.
"""
import os
import copy
import yaml

BASE = os.path.expanduser("~/ScoliCMF/configs/sc_pixel.yaml")
OUT = os.path.expanduser("~/ScoliCMF/configs")

# name, cond, proj, lambda_st, lambda_comp, lambda_roll, lambda_time
EXPS = [
    ("s2_base",            "base",  None,       0.0,  0.0, 0.0, 0.0),
    ("s3_st",              "base",  None,       0.05, 0.0, 0.0, 0.0),
    ("s4_comp",            "base",  None,       0.05, 0.1, 0.1, 0.0),
    ("s5_scpga_identity",  "scpga", "identity", 0.05, 0.1, 0.1, 0.01),
    ("s5_scpga_random",    "scpga", "random",   0.05, 0.1, 0.1, 0.01),
    ("s5_scpga_dct",       "scpga", "dct",      0.05, 0.1, 0.1, 0.01),
    ("s5_scpga_v1",        "scpga", "v1",       0.05, 0.1, 0.1, 0.01),
    ("s5b_scpga_v2",       "scpga", "v2",       0.05, 0.1, 0.1, 0.01),
    ("s5_scpga_v2_static", "scpga", "v2",       0.05, 0.1, 0.1, 0.01),  # dyn_off ablation
]


def main():
    base = yaml.safe_load(open(BASE))
    for name, cond, proj, st, comp, roll, tm in EXPS:
        dyn_off = name.endswith("_static")
        c = copy.deepcopy(base)
        c["model"]["cond"] = cond
        c["model"]["dyn_off"] = dyn_off
        if proj is not None:
            c["model"]["proj"] = proj
        c["meanflow"].update(lambda_st=st, lambda_comp=comp, lambda_roll=roll, lambda_time=tm)
        c["project"]["image_save_path"] = f"runs/{name}/images"
        c["project"]["checkpoint_path"] = f"runs/{name}/ckpts"
        c["project"]["log_file"] = f"runs/{name}/log.txt"
        c["experiment"] = name
        p = os.path.join(OUT, name + ".yaml")
        with open(p, "w") as f:
            f.write(f"# Experiment {name}: cond={cond} proj={proj} | ST={st} comp={comp} roll={roll} time={tm}\n")
            f.write("# Auto-generated by tools/gen_configs.py (one config = one method; do NOT hand-edit losses here).\n")
            yaml.safe_dump(c, f, sort_keys=False, allow_unicode=True)
        print("wrote", name, f"(cond={cond} proj={proj})")


if __name__ == "__main__":
    main()
